# version: '3.8' //Modern Docker Compose ignores it. 

services:
  livekit:
    image: livekit/livekit-server:latest
    container_name: audio-room-livekit

    ports:
      - "7880:7880"
      - "7881:7881"
      - "50000-50100:50000-50100/udp"

    command: --config /etc/livekit/livekit.yaml

    volumes:
      - ./livekit.yaml:/etc/livekit/livekit.yaml

    restart: unless-stopped